### ISSUE TITLE
Python and pytorch version ?

### ISSUE THREAD

**Issue by Michaelwhite34** [Rongjiehuang/ProDiff#12]
AppData\Local\Temp\pip-install-r50u5l8a\praat-parselmouth_4b359ba8e3b34072ab1c1d1b3e3b0992\setup.py", line 44, in run
          raise RuntimeError("CMake must be installed to build the following extensions: " + ", ".join(e.name for e in self.extensions))
      RuntimeError: CMake must be installed to build the following extensions: parselmouth
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> praat-parselmouth

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by Michaelwhite34** [comment]
On ubuntu, python 3.8. I used conda to install scipy and pip to install other dependences.

(prodiff) michael@michael-Legion-Y7000P-2019:~/Downloads/ProDiff$ CUDA_VISIBLE_DEVICES=$GPU python inference/ProDiff.py --config modules/ProDiff/config/prodiff.yaml --exp_name ProDiff --hparams="N=4,text='the invention of movable metal letters in the middle of the fifteenth century may justly be considered as the invention of the art of printing.'" --reset
Traceback (most recent call last):
  File "inference/ProDiff.py", line 2, in <module>
    from inference.base_tts_infer import BaseTTSInfer
ModuleNotFoundError: No module named 'inference'

**Comment by keelezibel** [comment]
@Michaelwhite34 you should install the dependencies first. During execution of the python scripts whether inference or others, you should run `export PYTHONPATH=.` so that the corresponding python scripts will check the current working directory for the paths.

**Comment by Michaelwhite34** [comment]
Now I get this

python data_gen/tts/bin/pre_align.py --config  egs/datasets/audio/1/base_text2mel.yaml
| Hparams chains:  ['egs/datasets/audio/1/base_text2mel.yaml']
| Hparams: 
binarization_args: {'shuffle': True}, binary_data_dir: data/binary/1, debug: False, exp_name: , infer: False, 
mel_loss: ssim:0.5|l1:0.5, min_frames: 128, num_spk: 2320, num_test_samples: 30, pitch_type: frame, 
pre_align_cls: egs.datasets.audio.libritts.pre_align.LibrittsPreAlign, processed_data_dir: data/processed/1, raw_data_dir: data/raw/1, test_num: 200, use_spk_id: True, 
validate: False, vocoder_ckpt: , work_dir: , 
Traceback (most recent call last):
  File "data_gen/tts/bin/pre_align.py", line 20, in <module>
    pre_align()
  File "data_gen/tts/bin/pre_align.py", line 14, in pre_align
    process_cls = getattr(importlib.import_module(pkg), cls_name)
  File "/home/michael/anaconda3/envs/prodiff/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/michael/Downloads/ProDiff/egs/datasets/audio/libritts/pre_align.py", line 3, in <module>
    from data_gen.tts.base_pre_align import BasePreAlign
ModuleNotFoundError: No module named 'data_gen.tts.base_pre_align'

**Comment by keelezibel** [comment]
@Michaelwhite34 this repo is not complete. If you check the folders, base_pre_align.py is not there. You will have to refer to the other repo for the pre-processing scripts. @Rongjiehuang it will be nice to include the pre-processing as well, I still have not figured out the pre-processing to be able to reproduce the same training outputs.

**Comment by keelezibel** [comment]
I have tried running the preproc with Natspeech repository as mentioned in the README. There are few minor changes but overall didnt encounter much issues. The processed dataset can be trained with the existing scripts in this repo. I am finetuning the Teacher with a different voice atm, let's see how it goes.
