### ISSUE TITLE
Issue running inference pipeline

### ISSUE THREAD

**Issue by keelezibel** [Rongjiehuang/ProDiff#7]
Tried to run the following command from the root project folder in Colab.
```
!CUDA_VISIBLE_DEVICES=$GPU python inference/ProDiff.py --config checkpoints/ProDiff/config.yaml --exp_name ProDiff --hparams="N=4,text='$txt'" --reset
```

but encountered the following error:
```
Traceback (most recent call last):
  File "inference/ProDiff.py", line 2, in <module>
    from base_tts_infer import BaseTTSInfer
  File "/content/ProDiff/inference/base_tts_infer.py", line 5, in <module>
    from tasks.tts.dataset_utils import FastSpeechWordDataset
ModuleNotFoundError: No module named 'tasks'
```

This is due to the relative reference of the folders. Any fixes on this? Will probably need to change the relative calls?

Thanks

**Comment by Rongjiehuang** [comment]
`export PYTHONPATH=.` before running this.
